{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "avalanche.serviceAccountName" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
{{- end -}}
