apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-node.fullname" . }}
  labels:
    {{- include "simple-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
  {{- end }}
  selector:
    {{- include "simple-node.selectorLabels" . | nindent 4 }}
