apiVersion: v1
description: Helm chart for avalanche node
name: avalanche
version: 0.0.2
appVersion: master
keywords:
- Avalanche
- validator
- blockchain
- AVAX
home: https://www.avax.network
sources:
- https://github.com/ava-labs/avalanchego
maintainers:
  - name: Ivan Genev
